const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const test = require('node:test');

const root = path.resolve(__dirname, '..');
const read = relativePath => fs.readFileSync(path.join(root, relativePath), 'utf8');

test('CM separates drag, open, and explicit page analysis actions', () => {
  const pet = read('frontend/src/shared/pet/StackyPet.jsx');
  const scriptPage = read('frontend/src/user/pages/ScriptPage.jsx');
  const css = read('frontend/src/shared/styles/global.css');

  assert.match(pet, /GripVertical/);
  assert.match(pet, /ScanSearch/);
  assert.match(pet, /ExternalLink/);
  assert.match(pet, /\bX\b/);
  assert.match(pet, /className="stacky-pet-drag-handle"/);
  assert.match(pet, /title="拖动移动 CM"/);
  assert.match(pet, /onPointerDown=\{handleDragStart\}/);
  assert.match(pet, /const draggedRef = useRef\(false\)/);
  assert.match(pet, /if \(draggedRef\.current\) \{[\s\S]*?return;/);
  assert.match(pet, /window\.addEventListener\('pointermove', move\)/);
  assert.match(pet, /window\.addEventListener\('pointerup', end\)/);
  assert.match(pet, /window\.removeEventListener\('pointermove', listeners\.move\)/);
  assert.match(pet, /didDrag\(/);
  assert.match(pet, /title="分析当前页面"/);
  assert.match(pet, /onClick=\{analyzeCurrentPage\}/);
  assert.match(pet, /function analyzeCurrentPage\(\) \{\s*sendQuestion\('请分析当前页面的内容，指出下一步最值得处理的事项。'\);/);
  assert.match(pet, /title="在 Agent 工作区继续"/);
  assert.match(pet, /window\.location\.href = `\/agent\?task=\$\{encodeURIComponent\(taskId\)\}`/);
  assert.match(pet, /const \[petTaskId, setPetTaskId\] = useState\(null\)/);
  assert.doesNotMatch(pet, /onDoubleClick/);
  assert.doesNotMatch(pet, /messages\.slice\(-4\)/);
  assert.match(pet, /messages\.map\(/);
  assert.match(pet, /getOverlayLayout\(/);
  assert.match(pet, /left: panelLayout\.left,[\s\S]*?top: panelLayout\.top,[\s\S]*?width: panelLayout\.width,[\s\S]*?height: panelLayout\.height/);
  assert.match(pet, /failedRequest/);
  assert.match(pet, /重新发送/);
  assert.match(pet, /const conversationRequestRef = useRef\(0\)/);
  assert.match(pet, /const historyRef = useRef\(null\)/);
  assert.match(pet, /conversationRequestRef\.current = requestId/);
  assert.match(pet, /conversationRequestRef\.current === requestId/);
  assert.match(pet, /if \(isCurrentConversationRequest\(requestId, accountSessionGeneration\)\) setAsking\(false\);/);
  assert.match(pet, /historyRef\.current\.scrollTop = historyRef\.current\.scrollHeight/);
  assert.match(pet, /className="stacky-agent-history" ref=\{historyRef\}/);
  assert.match(pet, /dispatchPetState/);
  assert.match(pet, /import \{[\s\S]*?dispatchPetState[\s\S]*?\} from '\.\/stacky';/);
  assert.match(pet, /clampOverlayToViewport/);
  assert.match(pet, /window\.addEventListener\('resize', keepOverlayVisible\)/);
  assert.match(pet, /问问 CM/);
  assert.match(pet, /关闭 CM 对话/);
  assert.match(pet, /function closeChat\(\) \{[\s\S]*?conversationRequestRef\.current \+= 1;[\s\S]*?setChatOpen\(false\);[\s\S]*?setAsking\(false\);[\s\S]*?spriteRef\.current\?\.focus\(\);/);
  assert.match(pet, /onClick=\{closeChat\}/);
  assert.match(pet, /if \(chatOpen && event\.key === 'Escape'\) closeChat\(\);/);
  assert.match(pet, /\}, \[chatOpen\]\);/);
  assert.match(pet, /role="dialog" aria-label="CM 互动"/);
  assert.match(pet, /应用到剧本/);
  assert.match(scriptPage, /dispatchPetContext/);
  assert.match(scriptPage, /PET_APPLY_EVENT/);
  assert.match(css, /\.stacky-agent-panel/);
  assert.match(css, /\.stacky-agent-input/);
  assert.match(css, /\.stacky-agent-close/);
  assert.match(css, /\.stacky-pet-drag-handle/);
  assert.match(css, /\.stacky-agent-history \{[\s\S]*?flex: 1;[\s\S]*?max-height: none;[\s\S]*?overflow-y: auto;/);
  assert.match(css, /\.cm-conversation-frame/);
  assert.match(css, /\.cm-conversation-frame::before/);
  assert.match(css, /linear-gradient\(to right, rgba\(160, 153, 216/);
});

test('Agent frontend API exposes task conversation endpoints', () => {
  const agentApi = read('frontend/src/shared/api/agent.js');

  assert.match(agentApi, /export function listAgentTasks\(\)\s*\{\s*return apiRequest\('\/api\/agent\/tasks'\);/);
  assert.match(agentApi, /export function createAgentTask\(\)\s*\{\s*return apiRequest\('\/api\/agent\/tasks', \{ method: 'POST' \}\);/);
  assert.match(agentApi, /export function getAgentTask\(id\)\s*\{\s*return apiRequest\(`\/api\/agent\/tasks\/\$\{encodeURIComponent\(id\)\}`\);/);
  assert.match(agentApi, /export function renameAgentTask\(id, title\)\s*\{\s*return apiRequest\(`\/api\/agent\/tasks\/\$\{encodeURIComponent\(id\)\}`, \{ method: 'PATCH', body: JSON\.stringify\(\{ title \}\) \}\);/);
  assert.match(agentApi, /export function clearAgentTask\(id\)\s*\{\s*return apiRequest\(`\/api\/agent\/tasks\/\$\{encodeURIComponent\(id\)\}\/messages`, \{ method: 'DELETE' \}\);/);
  assert.match(agentApi, /export function deleteAgentTask\(id\)\s*\{\s*return apiRequest\(`\/api\/agent\/tasks\/\$\{encodeURIComponent\(id\)\}`, \{ method: 'DELETE' \}\);/);
  assert.match(agentApi, /export function askAgent\(\{ taskId, prompt, context, skillIds = \[\] \}\)/);
  assert.match(agentApi, /JSON\.stringify\(\{ taskId, prompt, context, skillIds \}\)/);
  assert.doesNotMatch(agentApi, /getAgentHistory|clearAgentHistory/);
});

test('CM Agent renders account-scoped task conversations and keeps skills in the composer', () => {
  const page = read('frontend/src/user/pages/AgentPage.jsx');
  const pet = read('frontend/src/shared/pet/StackyPet.jsx');
  const css = read('frontend/src/shared/styles/global.css');

  assert.match(page, /listAgentTasks/);
  assert.match(page, /createAgentTask/);
  assert.match(page, /getAgentTask/);
  assert.match(page, /renameAgentTask/);
  assert.match(page, /clearAgentTask/);
  assert.match(page, /deleteAgentTask/);
  assert.match(page, /const \[tasks, setTasks\] = useState\(\[\]\)/);
  assert.match(page, /const \[activeTaskId, setActiveTaskId\] = useState\(null\)/);
  assert.match(page, /const \[activeTask, setActiveTask\] = useState\(null\)/);
  assert.match(page, /新建聊天/);
  assert.match(page, /agent-task-sidebar/);
  assert.match(page, /agent-task-row/);
  assert.match(page, /重命名任务/);
  assert.match(page, /clearAgentTask\(taskId\)/);
  assert.match(page, /deleteAgentTask\(taskId\)/);
  assert.match(page, /composerPanel === 'skill'/);
  assert.match(page, /新建我的技能/);
  assert.doesNotMatch(page, /<aside className="agent-skill-library/);
  assert.match(css, /\.agent-task-sidebar/);
  assert.match(css, /\.agent-task-row/);
  assert.doesNotMatch(pet, /getAgentHistory|clearAgentHistory/);
  assert.match(pet, /createAgentTask/);
  assert.match(pet, /getAgentTask/);
  assert.match(pet, /askAgent\(\{[\s\S]*?taskId/);
});

test('CM task workspace preserves active conversations and remains usable on narrow screens', () => {
  const page = read('frontend/src/user/pages/AgentPage.jsx');
  const pet = read('frontend/src/shared/pet/StackyPet.jsx');
  const css = read('frontend/src/shared/styles/global.css');

  assert.match(page, /const activeTaskIdRef = useRef\(null\)/);
  assert.match(page, /const mountedRef = useRef\(false\)/);
  assert.match(page, /mountedRef\.current = false;[\s\S]*?taskRequestRef\.current \+= 1;/);
  assert.match(page, /const initializationRequestRef = useRef\(0\)/);
  assert.match(page, /const initializationRequestId = \+\+initializationRequestRef\.current;/);
  assert.match(page, /taskRequestRef\.current !== initialTaskRequestId\) return undefined;/);
  assert.match(page, /initializationRequestRef\.current \+= 1;/);
  assert.match(page, /const skillsRequestRef = useRef\(0\)/);
  assert.match(page, /async function loadSkills\(\) \{[\s\S]*?const requestId = \+\+skillsRequestRef\.current;[\s\S]*?const result = await listAgentSkills\(\);[\s\S]*?if \(!mountedRef\.current \|\| skillsRequestRef\.current !== requestId\) return null;[\s\S]*?setSkills\(/);
  assert.match(page, /mountedRef\.current = false;[\s\S]*?taskRequestRef\.current \+= 1;[\s\S]*?initializationRequestRef\.current \+= 1;[\s\S]*?skillsRequestRef\.current \+= 1;/);
  assert.match(page, /activeTaskIdRef\.current = taskId/);
  assert.match(page, /if \(activeTaskIdRef\.current === taskId\) setActiveTask\(nextTask\)/);
  assert.match(page, /if \(event\.nativeEvent\.isComposing\) return;/);
  assert.match(page, /let requestId = taskRequestRef\.current;/);
  assert.match(page, /const createdTask = activeTask \? \{ task: activeTask, requestId \} : await createTask\(requestId\);/);
  assert.match(page, /taskId = task\.id;\s*requestId = createdTask\.requestId;/);
  assert.match(page, /if \(!mountedRef\.current \|\| taskRequestRef\.current !== expectedRequestId\) return null;/);
  assert.match(page, /function isCurrentTaskRequest\(\) \{\s*return mountedRef\.current && taskRequestRef\.current === requestId && activeTaskIdRef\.current === taskId;/);
  assert.match(page, /async function refreshTasks\(isCurrent = \(\) => true\) \{[\s\S]*?if \(!mountedRef\.current \|\| !isCurrent\(\)\) return null;[\s\S]*?setTasks\(nextTasks\);/);
  assert.match(page, /if \(!isCurrentTaskRequest\(\)\) return;\s*setActiveTask\(nextTask\);\s*await refreshTasks\(isCurrentTaskRequest\);\s*if \(isCurrentTaskRequest\(\)\) dispatchPetState\('success'\);/);
  assert.match(page, /\} catch \(error\) \{\s*if \(!isCurrentTaskRequest\(\)\) return;\s*message\.error/);
  assert.match(page, /\} finally \{\s*if \(isCurrentTaskRequest\(\)\) setAsking\(false\);/);
  assert.match(page, /taskRequestRef\.current === requestId/);
  assert.match(page, /async function clearCurrentTask\(\) \{[\s\S]*?taskRequestRef\.current \+= 1;[\s\S]*?await clearAgentTask\(taskId\)/);
  assert.match(pet, /const petTaskIdRef = useRef\(null\)/);
  assert.match(pet, /readCmTaskId\(username\)/);
  assert.match(pet, /writeCmTaskId\(username, taskId\)/);
  assert.match(pet, /writeCmTaskId\(username, petTaskIdRef\.current\)/);
  assert.match(pet, /当前对话已失效，已为你准备新对话。/);
  assert.match(pet, /contextRef\.current = normalizePetContext\(event\.detail\);/);
  assert.match(pet, /async function loadPetTask\(taskId\)/);
  assert.match(pet, /setFailedRequest\(\{ prompt: content, error: message \}\)/);
  assert.match(pet, /onClick=\{\(\) => sendQuestion\(failedRequest\.prompt\)\}/);
  assert.doesNotMatch(pet, /listAgentTasks/);
  assert.match(pet, /getAgentTask/);
  assert.match(css, /\.agent-page \{[^}]*min-height: 0;[^}]*overflow: auto;[^}]*overflow-x: hidden;[^}]*\}/);
  assert.match(css, /@media \(max-width: 860px\) \{[\s\S]*?\.agent-page \{[^}]*min-height: 0;[^}]*overflow: auto;[^}]*overflow-x: hidden;[^}]*\}/);
  assert.match(css, /\[data-theme='light'\] \.stacky-agent-close[^}]*background: #ffffff;[^}]*color: var\(--legacy-text\);/);
  assert.doesNotMatch(pet, /getChatPanelLayout/);
  assert.match(pet, /const \[viewport, setViewport\] = useState\(getViewport\)/);
  assert.match(pet, /setViewport\(getViewport\(\)\)/);
  assert.match(pet, /stacky-agent-panel--opens-\$\{panelLayout\.placement\}/);
  assert.match(pet, /style=\{panelStyle\}/);
  assert.match(css, /\.stacky-agent-panel \{[^}]*position: fixed;[^}]*display: flex;[^}]*flex-direction: column;/);
  assert.match(css, /\.stacky-agent-panel--opens-right/);
  assert.match(css, /\.stacky-agent-panel--opens-left/);
});

test('CM task UI resets across accounts and protects the composer while task details load', () => {
  const page = read('frontend/src/user/pages/AgentPage.jsx');
  const pet = read('frontend/src/shared/pet/StackyPet.jsx');
  const layout = read('frontend/src/shared/layouts/UserLayout.jsx');
  const css = read('frontend/src/shared/styles/global.css');

  assert.match(layout, /const accountSessionKey = username \|\| 'anonymous';/);
  assert.match(layout, /const accountSessionGenerationRef = useRef\(0\)/);
  assert.match(layout, /useEffect\(\(\) => \{\s*document\.documentElement\.dataset\.theme = theme;[\s\S]*?\}, \[theme\]\);/);
  assert.match(layout, /useEffect\(\(\) => \{\s*let cancelled = false;\s*const sessionGeneration = \+\+accountSessionGenerationRef\.current;\s*const sessionToken = getToken\(\);/);
  assert.match(layout, /const sessionToken = getToken\(\);/);
  assert.match(layout, /accountSessionGenerationRef\.current === sessionGeneration[\s\S]*?getToken\(\) === sessionToken/);
  assert.match(layout, /const expiredToken = event\?\.detail\?\.token;[\s\S]*?const currentToken = getToken\(\);[\s\S]*?if \(expiredToken\) \{[\s\S]*?if \(!currentToken \|\| expiredToken !== currentToken\) return;[\s\S]*?\} else if \(!sessionToken \|\| currentToken \|\| cancelled \|\| accountSessionGenerationRef\.current !== sessionGeneration\) \{/);
  assert.match(layout, /if \(!isCurrentSession\(\)\) return;[\s\S]*?setUsername\(currentAccount\.username\);/);
  assert.match(layout, /cancelled = true;[\s\S]*?accountSessionGenerationRef\.current \+= 1;/);
  assert.match(layout, /<Fragment key=\{accountSessionKey\}>[\s\S]*?<section className="legacy-content">\{content\}<\/section>[\s\S]*?<StackyPet username=\{username\} accountSessionKey=\{accountSessionKey\} \/>[\s\S]*?<\/Fragment>/);
  assert.match(pet, /export function StackyPet\(\{ username, accountSessionKey \}\)/);
  assert.match(pet, /const accountSessionGenerationRef = useRef\(0\)/);
  assert.match(pet, /accountSessionGenerationRef\.current \+= 1;/);
  assert.match(pet, /function isCurrentConversationRequest\(requestId, accountSessionGeneration\) \{[\s\S]*?conversationRequestRef\.current === requestId[\s\S]*?accountSessionGenerationRef\.current === accountSessionGeneration;/);
  assert.match(pet, /function dispatchConversationPetState\(requestId, accountSessionGeneration, nextState\) \{[\s\S]*?isCurrentConversationRequest\(requestId, accountSessionGeneration\)[\s\S]*?dispatchPetState\(nextState\);/);
  assert.match(pet, /return \(\) => \{[\s\S]*?accountSessionGenerationRef\.current \+= 1;[\s\S]*?conversationRequestRef\.current \+= 1;[\s\S]*?\};\n  \}, \[accountSessionKey, username\]\);/);
  assert.match(pet, /const accountSessionGeneration = accountSessionGenerationRef\.current;/);
  assert.match(pet, /if \(!isCurrentConversationRequest\(requestId, accountSessionGeneration\)\) return null;/);
  assert.match(pet, /if \(!taskId \|\| !isCurrentConversationRequest\(requestId, accountSessionGeneration\)\) return;/);
  assert.match(pet, /if \(!isCurrentConversationRequest\(requestId, accountSessionGeneration\)\) return;[\s\S]*?petTaskIdRef\.current = result\.task\?\.id \|\| taskId;[\s\S]*?writeCmTaskId\(username, petTaskIdRef\.current\);/);
  assert.match(pet, /function clearPetTask\(messageText = '', accountSessionGeneration = accountSessionGenerationRef\.current\) \{[\s\S]*?if \(accountSessionGenerationRef\.current !== accountSessionGeneration\) return;/);
  assert.match(pet, /\}, \[accountSessionKey, username\]\);/);
  assert.match(page, /new URLSearchParams\(window\.location\.search\)\.get\('task'\)/);
  assert.match(page, /function syncTaskUrl\(taskId, historyMode = 'replace'\)/);
  assert.match(page, /if \(historyMode === 'push'\) \{\s*window\.history\.pushState\(\{\}, '', nextUrl\);/);
  assert.match(page, /window\.history\.replaceState\(\{\}, '', nextUrl\)/);
  assert.match(page, /const nextUrl = taskId \? `\/agent\?task=\$\{encodeURIComponent\(taskId\)\}` : '\/agent';/);
  assert.match(page, /async function selectTask\(taskId, \{ historyMode = 'replace' \} = \{\}\)/);
  assert.match(page, /async function selectTask\(taskId, \{ historyMode = 'replace' \} = \{\}\) \{\s*syncTaskUrl\(taskId, historyMode\);/);
  assert.match(page, /getAgentTask\(taskId\);\s*if \(mountedRef\.current && taskRequestRef\.current === requestId\) activateTask\(result\.task \|\| null, \{ historyMode: 'none' \}\);/);
  assert.match(page, /onClick=\{\(\) => selectTask\(task\.id, \{ historyMode: 'push' \}\)\}/);
  assert.match(page, /async function createTask\(expectedRequestId = taskRequestRef\.current, \{ historyMode = 'push' \} = \{\}\)/);
  assert.match(page, /onClick=\{\(\) => createTask\(\)\}/);
  assert.match(page, /selectTask\(requestedTask\.id, \{ historyMode: 'none' \}\)/);
  assert.match(page, /const requestedTask = nextTasks\.find\(task => task\.id === requestedTaskId\);/);
  assert.match(page, /window\.addEventListener\('popstate', selectHistoryTask\);/);
  assert.match(page, /const requestedTask = tasksRef\.current\.find\(task => task\.id === requestedTaskId\);[\s\S]*?if \(requestedTask\) \{[\s\S]*?selectTask\(requestedTask\.id, \{ historyMode: 'none' \}\)[\s\S]*?return;[\s\S]*?if \(activeTaskIdRef\.current !== null \|\| taskDetailLoadingRef\.current\) \{[\s\S]*?taskRequestRef\.current \+= 1;[\s\S]*?activateTask\(null, \{ historyMode: 'none' \}\);/);
  assert.match(page, /error\?\.status === 404/);
  assert.match(page, /const \[taskDetailLoading, setTaskDetailLoading\] = useState\(false\)/);
  assert.match(page, /const taskDetailLoadingRef = useRef\(false\)/);
  assert.match(page, /taskDetailLoadingRef\.current = true;/);
  assert.match(page, /if \(!prompt \|\| asking \|\| taskDetailLoadingRef\.current\) return;/);
  assert.match(page, /role="status">正在读取任务列表\.\.\.<\/div>/);
  assert.match(page, /role="status">正在读取任务详情\.\.\.<\/div>/);
  assert.match(page, /disabled=\{taskDetailLoading\}/);
  assert.match(page, /aria-expanded=\{composerMenuOpen\}/);
  assert.match(page, /aria-controls=\{composerMenuId\}/);
  assert.match(page, /id=\{composerMenuId\} role="menu"/);
  assert.match(page, /role="menuitem"/);
  assert.match(page, /event\.key === 'Escape'/);
  assert.match(page, /composerTriggerRef\.current\?\.focus\(\)/);
  assert.doesNotMatch(css, /--stacky-agent-panel-left|--stacky-agent-panel-width/);
});

test('authentication expiry only clears the session that issued the 401', () => {
  const client = read('frontend/src/shared/api/client.js');
  const layout = read('frontend/src/shared/layouts/UserLayout.jsx');

  assert.match(client, /const token = getToken\(\);/);
  assert.match(client, /if \(getToken\(\) === token\) \{[\s\S]*?new CustomEvent\('qiantie:auth-expired', \{ detail: \{ token \} \}\)[\s\S]*?setToken\(''\);[\s\S]*?localStorage\.removeItem\('auth_username'\);/);
  assert.match(client, /if \(response\.status === 401[\s\S]*?throw new Error\('登录已失效，请重新登录'\);/);
  assert.match(layout, /const expiredToken = event\?\.detail\?\.token;[\s\S]*?const currentToken = getToken\(\);[\s\S]*?if \(expiredToken\) \{[\s\S]*?if \(!currentToken \|\| expiredToken !== currentToken\) return;[\s\S]*?\} else if \(!sessionToken \|\| currentToken \|\| cancelled \|\| accountSessionGenerationRef\.current !== sessionGeneration\) \{/);
});

test('CM pages dispatch bounded operational context without reading novel iframe content', () => {
  const script = read('frontend/src/user/pages/ScriptPage.jsx');
  const tts = read('frontend/src/user/pages/TtsPage.jsx');
  const shuihuo = read('frontend/src/user/pages/ShuihuoProductionPage.jsx');
  const novel = read('frontend/src/user/pages/NovelPanelPage.jsx');

  assert.match(script, /pagePath: '\/script'/);
  assert.match(script, /characterCount,[\s\S]*?sceneCount,[\s\S]*?generationStage,[\s\S]*?hasOutput/);
  assert.match(script, /\}, \[extractInfo, output, generationStage\]\);/);
  assert.match(tts, /import \{ dispatchPetContext, dispatchPetState \} from '\.\.\/\.\.\/shared\/pet\/stacky';/);
  assert.match(tts, /page: '配音',[\s\S]*?pagePath: '\/tts'/);
  assert.match(tts, /cardCount: cards\.length,[\s\S]*?generatedCount,[\s\S]*?defaultVoice:[\s\S]*?speed:[\s\S]*?pitch:/);
  assert.match(shuihuo, /page: '水货生产',[\s\S]*?pagePath: '\/shuihuo-production'/);
  assert.match(shuihuo, /projectId:[\s\S]*?projectName,[\s\S]*?segmentCount:[\s\S]*?assetCount:[\s\S]*?view/);
  assert.match(novel, /page: '小说面板',[\s\S]*?pagePath: '\/novel-panel'/);
  assert.match(novel, /entities: \{ projectId: opaqueProjectId, stage \}/);
  assert.doesNotMatch(novel, /contentDocument|contentWindow\?\.(?:document|location)|srcdoc/);
});

test('CM pages discard stale work and bound the novel panel bridge', () => {
  const script = read('frontend/src/user/pages/ScriptPage.jsx');
  const tts = read('frontend/src/user/pages/TtsPage.jsx');
  const shuihuo = read('frontend/src/user/pages/ShuihuoProductionPage.jsx');
  const novel = read('frontend/src/user/pages/NovelPanelPage.jsx');

  assert.match(script, /const requestGenerationRef = useRef\(\{ workflow: 0, narrate: 0 \}\)/);
  assert.match(script, /const sourceGenerationRef = useRef\(0\)/);
  assert.match(script, /function invalidateRequests\(\) \{\s*sourceGenerationRef\.current \+= 1;/);
  assert.match(script, /Object\.hasOwn\(changed, 'novelText'\)[\s\S]*?invalidateRequests\(\);/);
  assert.match(script, /if \(!isCurrentRequest\(requestId\)\) return;/);
  assert.match(script, /URL\.revokeObjectURL\(nextAudioUrl\);/);
  assert.match(tts, /const cardRequestRef = useRef\(new Map\(\)\)/);
  assert.match(tts, /function nextCardRequest\(id\)/);
  assert.match(tts, /if \(!isCurrentCardRequest\(id, requestId\) \|\| !cardStillExists\(id\)\) \{/);
  assert.match(tts, /nextCardRequest\(id\);[\s\S]*?cardRequestRef\.current\.delete\(id\);/);
  assert.match(tts, /audioUrlsRef\.current\.delete\(nextAudioUrl\);[\s\S]*?URL\.revokeObjectURL\(nextAudioUrl\);/);
  assert.match(shuihuo, /const projectRequestRef = useRef\(0\)/);
  assert.match(shuihuo, /const refreshRequestRef = useRef\(0\)/);
  assert.match(shuihuo, /const requestId = \+\+projectRequestRef\.current;/);
  assert.match(shuihuo, /async function handleDelete\(project\) \{[\s\S]*?projectRequestRef\.current \+= 1;/);
  assert.match(shuihuo, /projectRequestRef\.current !== requestId\) return;/);
  assert.match(shuihuo, /const requestId = \+\+refreshRequestRef\.current;/);
  assert.match(shuihuo, /refreshRequestRef\.current !== requestId\) return null;/);
  assert.match(novel, /const MAX_REQUEST_BODY_BYTES = 64 \* 1024;/);
  assert.match(novel, /const MAX_REQUEST_ID_LENGTH = 120;/);
  assert.match(novel, /const MAX_HEADER_VALUE_LENGTH = 512;/);
  assert.match(novel, /const MAX_ACTIVE_CONTROLLERS = 8;/);
  assert.match(novel, /const MAX_RESPONSE_BODY_BYTES = 2 \* 1024 \* 1024;/);
  assert.match(novel, /const MAX_RESPONSE_HEADER_BYTES = 8 \* 1024;/);
  assert.match(novel, /async function readResponseBytes\(response\)/);
  assert.match(novel, /size > MAX_RESPONSE_BODY_BYTES/);
  assert.match(novel, /function boundedResponseHeaders\(headers\)/);
  assert.match(novel, /utf8ByteLength\(data\.body\) > MAX_REQUEST_BODY_BYTES\) return \{ error: 413/);
  assert.match(novel, /value\.length > MAX_HEADER_VALUE_LENGTH\) return \{ error: 413/);
  assert.match(novel, /controllersRef\.current\.size >= MAX_ACTIVE_CONTROLLERS/);
  assert.match(novel, /controllersRef\.current\.delete\(data\.id\);/);
  assert.match(novel, /status: request\.error/);
});
