const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const source = fs.readFileSync(path.resolve(__dirname, '../server.js'), 'utf8');
assert.match(source, /v783031-regeneration-middleware/);
assert.match(source, /\/api\/novel-panel\/regenerate-scene-outline/);
assert.match(source, /createV783031RegenerationMiddleware\(\)/);
assert.match(source, /v783031-outline-route/);
assert.match(source, /const \{ apiAuth \} = require\('\.\/middleware\/auth'\)/);
assert.match(source, /\/api\/novel-panel\/outline-scenes/);
assert.match(source, /createV783031OutlineHandler\(\{ coreApp \}\)/);
assert.match(source, /app\.locals\.authRuntime\s*=\s*coreApp\.locals\.authRuntime/);
const outline = source.indexOf('/api/novel-panel/outline-scenes');
const regen = source.indexOf('/api/novel-panel/regenerate-scene-outline');
const core = source.indexOf('app.use(coreApp)');
assert.ok(outline >= 0 && core >= 0 && outline < core, 'V31 director outline handler must run before coreApp');
assert.ok(regen >= 0 && core >= 0 && regen < core, 'V31 patch middleware must run before coreApp');
console.log('V78.3.0.31 server mounts regression: PASS');
