import { Alert, Button, Modal, Select, Space, Switch, Tabs, message } from 'antd';
import { useEffect, useMemo, useState } from 'react';
import { listSystemPresetCatalog, saveBatchSettings } from '../../../shared/api/batchFactoryV11';

const slots=[['extraction','人物场景提取','script.extract'],['character','人物提示词','batch.character-meta'],['scene','场景提示词','batch.scene-meta'],['prop','道具提示词','batch.prop-meta']];
const scopes=[{value:'all',label:'全部小说'},{value:'unfinished',label:'未完成小说'},{value:'custom',label:'自定义小说'}];
const blank=()=>({presetId:'',presetName:'',presetSlot:'',presetVersion:null});
const clean=v=>{const x=v&&typeof v==='object'?v:{}, id=String(x.presetId||'').trim();return id?{presetId:id,presetName:String(x.presetName||''),presetSlot:String(x.presetSlot||''),presetVersion:Number(x.presetVersion)||null}:blank();};
const scope=(v,on)=>({enabled:typeof v?.enabled==='boolean'?v.enabled:on,scope:v?.scope||'all',bookIds:Array.isArray(v?.bookIds)?v.bookIds:[]});
function normalize(v,batch){const c=v&&typeof v==='object'?v:{},a=c.assets||{},n=c.constraints||{},video=c.video||{},visual=c.visual||{};return {assets:{...scope(a,true),...Object.fromEntries(slots.map(([k])=>[k,clean(a[k])]))},constraints:{...scope(n,false),selections:(Array.isArray(n.selections)?n.selections:[]).map(clean).filter(x=>x.presetId)},video:{...scope(video,true),...clean(video),fixedSingleVideo:video.fixedSingleVideo??batch?.settingsState?.patch?.fixedSingleVideo===true},visual:{...scope(visual,false),...clean(visual)}};}
const opts=r=>r.map(x=>({value:x.id,label:`${x.name||x.id} · v${x.version||1}`}));
const pick=(r,id)=>{const x=r.find(y=>y.id===id);return x?{presetId:x.id,presetName:x.name||x.id,presetSlot:x.slot||'',presetVersion:x.version||1}:blank();};
function Range({value,books,onChange}){return <><label className="batch-factory-ai-field"><span>范围</span><Select value={value.scope} options={scopes} onChange={scope=>onChange({scope,bookIds:scope==='custom'?value.bookIds:[]})}/></label>{value.scope==='custom'?<label className="batch-factory-ai-field"><span>指定小说</span><Select mode="multiple" value={value.bookIds} options={books.map(x=>({value:x.id,label:`${x.title||'未命名'} · ${x.bookId||'—'}`}))} onChange={bookIds=>onChange({bookIds})}/></label>:null}</>}
function Rule({title,desc,value,books,onChange,children}){return <div className="batch-factory-ai-module"><div className="batch-factory-ai-module-head"><div><b>{title}</b><p>{desc}</p></div><Switch checked={value.enabled===true} onChange={enabled=>onChange({enabled})}/></div>{value.enabled?<div className="batch-factory-ai-module-body">{children}<Range value={value} books={books} onChange={onChange}/></div>:<p className="batch-factory-ai-disabled">当前模块未启用，不会参与本次统一 AI 推理。</p>}</div>}
function Field({label,records,value,onChange,loading}){return <label className="batch-factory-ai-field"><span>{label}</span><Select allowClear showSearch loading={loading} value={value?.presetId||undefined} options={opts(records)} placeholder="选择已发布预设词" onChange={id=>onChange(pick(records,id))}/></label>}
export function BatchFactoryAiReasoningModal({open,batch,books,onClose,onSaved,onRun,running,runAvailable,runReason}){
 const [config,setConfig]=useState(()=>normalize({},batch)),[catalog,setCatalog]=useState({script:[],batch:[]}),[loading,setLoading]=useState(false),[error,setError]=useState(''),[saving,setSaving]=useState(false);const revision=Number(batch?.settingsState?.revision||0), usable=useMemo(()=> (books||[]).filter(x=>String(x.sourceText||'').trim()),[books]);
 useEffect(()=>{if(open)setConfig(normalize(batch?.settingsState?.patch?.aiPromptConfig,batch));},[open,batch?.id,batch?.settingsState?.revision]);
 useEffect(()=>{if(!open)return;let active=true;setLoading(true);setError('');Promise.all([listSystemPresetCatalog('script'),listSystemPresetCatalog('batch-factory')]).then(([s,b])=>active&&setCatalog({script:Array.isArray(s?.catalog)?s.catalog:[],batch:Array.isArray(b?.catalog)?b.catalog:[]})).catch(e=>active&&setError(e?.message||'个人中心系统预设词读取失败')).finally(()=>active&&setLoading(false));return()=>{active=false};},[open]);
 const extract=useMemo(()=>catalog.script.filter(x=>x.kind==='base'&&x.extractionPreset===true),[catalog.script]), constraints=useMemo(()=>catalog.script.filter(x=>x.kind==='addon'&&x.constraintCategory),[catalog.script]), bySlot=key=>catalog.batch.filter(x=>x.slot===slots.find(y=>y[0]===key)?.[2]), video=useMemo(()=>catalog.batch.filter(x=>x.slot==='batch.video-meta'),[catalog.batch]), visual=useMemo(()=>catalog.batch.filter(x=>x.slot==='batch.visual-meta'),[catalog.batch]);
 const patch=(key,v)=>setConfig(c=>({...c,[key]:{...c[key],...v}}));
 async function save(){if(!batch?.id)return false;setSaving(true);try{await saveBatchSettings(batch.id,{patch:{aiPromptConfig:config,fixedSingleVideo:config.video.fixedSingleVideo===true},expectedRevision:revision});await onSaved?.();message.success('已保存当前批量的 AI 推理规则。');return true}catch(e){message.error(e?.message||'保存 AI 推理配置失败');return false}finally{setSaving(false)}}
 const items=[
 {key:'assets',label:'资产设置',children:<Rule title="人物场景提示词" desc="提取与人物、场景、道具各自对标对应预设词。" value={config.assets} books={usable} onChange={v=>patch('assets',v)}>{slots.map(([k,l])=><Field key={k} label={l} records={k==='extraction'?extract:bySlot(k)} value={config.assets[k]} loading={loading} onChange={v=>patch('assets',{[k]:v})}/>)}</Rule>},
 {key:'constraints',label:'约束设置',children:<Rule title="生产约束" desc="对标剧本生成约束设置，可多选。" value={config.constraints} books={usable} onChange={v=>patch('constraints',v)}><label className="batch-factory-ai-field"><span>剧本生成约束</span><Select mode="multiple" loading={loading} value={config.constraints.selections.map(x=>x.presetId)} options={opts(constraints)} onChange={ids=>patch('constraints',{selections:ids.map(id=>pick(constraints,id))})}/></label></Rule>},
 {key:'video',label:'视频设置',children:<Rule title="视频提示词" desc="只约束 video_desc、动作和运镜。" value={config.video} books={usable} onChange={v=>patch('video',v)}><Field label="视频提示词" records={video} value={config.video} loading={loading} onChange={v=>patch('video',v)}/><label className="batch-factory-ai-field"><span>固定开头</span><Select value={config.video.fixedSingleVideo?'single':'multiple'} options={[{value:'single',label:'单个 VIDEO'},{value:'multiple',label:'多个 VIDEO'}]} onChange={v=>patch('video',{fixedSingleVideo:v==='single'})}/></label></Rule>},
 {key:'visual',label:'画面设置',children:<Rule title="画面提示词" desc="默认关闭，仅用于画面图片，绝不写入视频提示词。" value={config.visual} books={usable} onChange={v=>patch('visual',v)}><Field label="画面提示词" records={visual} value={config.visual} loading={loading} onChange={v=>patch('visual',v)}/></Rule>}
 ];
 return <Modal title="AI 推理" open={open} onCancel={onClose} width={900} className="batch-factory-ai-modal" footer={<Space><Button onClick={onClose}>取消</Button><Button loading={saving} onClick={save}>保存当前作品配置</Button><Button type="primary" loading={running} disabled={!runAvailable||saving||running||!usable.length} title={runAvailable?'先保存选择的系统预设词，再执行统一 AI 推理。':runReason} onClick={async()=>{if(await save())await onRun?.()}}>保存并统一生成</Button></Space>}><Alert type="info" showIcon message="从个人中心的已发布预设词选择" description="人物场景提取和约束对标剧本生成；人物、场景、道具、视频和画面都有固定槽位。预设正文不展示给浏览器。"/>{error?<Alert type="warning" showIcon message="系统预设词读取失败" description={error}/>:null}<Tabs items={items}/>{!runAvailable?<Alert type="warning" showIcon message="当前不能执行 AI 推理" description={runReason||'请先完成引擎配置。'}/>:null}</Modal>;
}
