import { SettingOutlined } from '@ant-design/icons';
import { Alert, Button, Input, Modal, Select, Space, Switch, Tabs, Tooltip, message } from 'antd';
import { useEffect, useMemo, useState } from 'react';
import { createConfigVersion, listSystemPresetCatalog, renameConfigVersion, saveBatchSettings } from '../../../shared/api/batchFactoryV11';

const slots=[['extraction','人物场景道具提示词','script.asset-extraction']];
// Batch Factory extracts people, scenes and props in one request.  Keep the
// default on the same published extraction preset used by script generation;
// an older batch with no saved reasoning configuration must not silently fall
// back to the abbreviated Go-only extraction wording.
const defaultAssetExtraction=()=>({presetId:'script-extract-assets',presetName:'人物场景道具提取',presetSlot:'script.asset-extraction',presetVersion:null,constraintCategory:''});
const defaultVideoPrompt=()=>({presetId:'batch-video-meta',presetName:'分镜元提示词（自动组合）',presetSlot:'batch.video-meta',presetVersion:null,constraintCategory:''});
const scopes=[{value:'all',label:'全部小说'},{value:'unfinished',label:'未完成小说'},{value:'custom',label:'自定义小说'}];
const defaultConstraintCategories=['prefix','quality','restriction','negative'];
const blank=()=>({presetId:'',presetName:'',presetSlot:'',presetVersion:null,constraintCategory:''});
const clean=v=>{const x=v&&typeof v==='object'?v:{}, id=String(x.presetId||'').trim();return id?{presetId:id,presetName:String(x.presetName||''),presetSlot:String(x.presetSlot||''),presetVersion:Number(x.presetVersion)||null,constraintCategory:String(x.constraintCategory||'')}:blank();};
const scope=(v,on)=>({enabled:typeof v?.enabled==='boolean'?v.enabled:on,scope:v?.scope||'all',bookIds:Array.isArray(v?.bookIds)?v.bookIds:[]});
function normalize(v,batch){
  const c=v&&typeof v==='object'?v:{},a=c.assets||{},n=c.constraints||{},derivedOpening=c.derivedOpening||{},video=c.video||{},visual=c.visual||{};
  const assetSelections=Object.fromEntries(slots.map(([key])=>{
    const selected=clean(a[key]);
    return [key,key==='extraction'&&!selected.presetId?defaultAssetExtraction():selected];
  }));
  return {
    assets:{...a,...scope(a,true),...assetSelections},
    constraints:{...scope(n,true),baseSetup:{enabled:n.baseSetup?.enabled!==false},selections:(Array.isArray(n.selections)?n.selections:[]).map(clean).filter(x=>x.presetId),enabledCategories:Array.isArray(n.enabledCategories)?n.enabledCategories.map(String).filter(Boolean):defaultConstraintCategories},
    hook:{...scope(c.hook,false),...clean(c.hook)},
    originalDirector:{...scope(c.originalDirector,false),...clean(c.originalDirector)},
    viralDirector:{...scope(c.viralDirector,false),...clean(c.viralDirector)},
    derivedOpening:{...scope(derivedOpening,true),...clean(derivedOpening)},
    video:{...scope(video,true),...(clean(video).presetId?clean(video):defaultVideoPrompt()),enabled:true},
    visual:{...scope(visual,false),...clean(visual)}
  };
}
const presetLabel=x=>String(x?.name||x?.presetName||x?.label||x?.id||'').trim();
const opts=r=>(Array.isArray(r)?r:[]).map(x=>({value:x.id,disabled:x.disabled===true,label:<span className="batch-factory-preset-option"><span>{presetLabel(x)}</span><small>v{x.version||1}</small></span>}));
// An old saved book may have an ID-only selection or an archived catalog entry.
// Keep its frozen name visible instead of letting Select render the raw ID.
const withCurrentOption=(records,value)=>{const current=value?.presetId?{id:value.presetId,name:'预设已失效',version:value.presetVersion,disabled:true}:null;return current&&!records.some(item=>item.id===current.id)?[current,...records]:records;};
const pick=(r,id)=>{const x=r.find(y=>y.id===id);return x?{presetId:x.id,presetName:x.name||x.id,presetSlot:x.slot||'',presetVersion:x.version||1,constraintCategory:x.constraintCategory||''}:blank();};
const aiPresetConfig=version=>{const raw=version?.config&&typeof version.config==='object'?version.config:{};return raw.type==='ai-reasoning-preset'&&raw.aiPromptConfig&&typeof raw.aiPromptConfig==='object'?raw.aiPromptConfig:null;};
function Range({value,books,onChange}){return <><label className="batch-factory-ai-field"><span>范围</span><Select value={value.scope} options={scopes} onChange={scope=>onChange({scope,bookIds:scope==='custom'?value.bookIds:[]})}/></label>{value.scope==='custom'?<label className="batch-factory-ai-field"><span>指定小说</span><Select mode="multiple" value={value.bookIds} options={books.map(x=>({value:x.id,label:`${x.title||'未命名'} · ${x.bookId||'—'}`}))} onChange={bookIds=>onChange({bookIds})}/></label>:null}</>}
function Rule({title,desc,value,books,onChange,children,showRange=true,required=false}){const enabled=required||value.enabled===true;return <div className="batch-factory-ai-module"><div className="batch-factory-ai-module-head"><div><b>{title}</b><p>{desc}</p></div>{required?null:<Switch checked={enabled} onChange={enabled=>onChange({enabled})}/>}</div>{enabled?<div className="batch-factory-ai-module-body">{children}{showRange?<Range value={value} books={books} onChange={onChange}/>:<p className="batch-factory-ai-global-rule">开启的层会统一作用于当前批量内全部小说，单书配置只可额外覆盖，不会在这里拆分范围。</p>}</div>:<p className="batch-factory-ai-disabled">当前模块未启用，不会参与本次统一 AI 推理。</p>}</div>}
function Field({label,records,value,onChange,loading,required=false}){const options=withCurrentOption(records,value,label);return <label className="batch-factory-ai-field"><span>{label}</span><Select allowClear={!required} showSearch loading={loading} value={value?.presetId||undefined} options={opts(options)} placeholder={required?'请选择已发布视频提示词':'选择已发布预设词'} onChange={id=>onChange(pick(options,id))}/></label>}
function ConstraintLayers({value,records,loading,onChange}){const layers=[['baseSetup','基础设定（人物 / 场景）'],['prefix','画面前缀词'],['quality','画面约束提示词'],['restriction','画面限制'],['negative','负面提示词']];const selected=category=>value.selections.find(item=>item.constraintCategory===category)||blank();const enabled=category=>category==='baseSetup'?value.baseSetup?.enabled===true:value.enabledCategories.includes(category);const update=(category,patch)=>{const current=selected(category),next={...current,...patch,constraintCategory:category};const rest=value.selections.filter(item=>item.constraintCategory!==category);const enabledCategories=[...new Set([...value.enabledCategories,category])];onChange({selections:next.presetId?[...rest,next]:rest,enabledCategories});};const toggle=(category,on)=>category==='baseSetup'?onChange({baseSetup:{enabled:on}}):onChange({enabledCategories:on?[...new Set([...value.enabledCategories,category])]:value.enabledCategories.filter(item=>item!==category),selections:on?value.selections:value.selections.filter(item=>item.constraintCategory!==category)});return <div className="batch-factory-constraint-layers">{layers.map(([category,label])=>{const current=selected(category),options=withCurrentOption(records.filter(item=>item.constraintCategory===category),current,label);return <div className="batch-factory-constraint-layer" key={category}><Space align="center" style={{width:'100%',justifyContent:'space-between'}}><b>{label}</b><Switch checked={enabled(category)} onChange={on=>toggle(category,on)}/></Space>{category!=='baseSetup'&&enabled(category)?<Select allowClear showSearch loading={loading} value={current.presetId||undefined} options={opts(options)} placeholder="选择系统预设" onChange={id=>update(category,pick(options,id))} style={{width:'100%',marginTop:8}}/>:null}</div>;})}</div>}

export function BatchFactoryAiReasoningModal({open,batch,books,presetVersions,onClose,onSaved,onPresetsChanged,onRun,running,runAvailable,runReason}){
	 const [config,setConfig]=useState(()=>normalize({},batch)),[catalog,setCatalog]=useState({script:[],batch:[]}),[loading,setLoading]=useState(false),[error,setError]=useState(''),[saving,setSaving]=useState(false),[presetOpen,setPresetOpen]=useState(false),[presetName,setPresetName]=useState(''),[selectedPresetId,setSelectedPresetId]=useState(''),[presetBusy,setPresetBusy]=useState(false);const revision=Number(batch?.settingsState?.revision||0), usable=useMemo(()=> (books||[]).filter(x=>String(x.sourceText||'').trim()),[books]), aiPresets=useMemo(()=> (Array.isArray(presetVersions)?presetVersions:[]).filter(version=>Boolean(aiPresetConfig(version))),[presetVersions]), selectedPreset=aiPresets.find(version=>version.id===selectedPresetId)||null;
 useEffect(()=>{if(open)setConfig(normalize(batch?.settingsState?.patch?.aiPromptConfig,batch));},[open,batch?.id,batch?.settingsState?.revision]);
 useEffect(()=>{if(!open)return;let active=true;setLoading(true);setError('');Promise.all([listSystemPresetCatalog('script'),listSystemPresetCatalog('batch-factory')]).then(([s,b])=>active&&setCatalog({script:Array.isArray(s?.catalog)?s.catalog:[],batch:Array.isArray(b?.catalog)?b.catalog:[]})).catch(e=>active&&setError(e?.message||'个人中心系统预设词读取失败')).finally(()=>active&&setLoading(false));return()=>{active=false};},[open]);
 const extract=useMemo(()=>catalog.script.filter(x=>x.slot==='script.asset-extraction'),[catalog.script]), constraints=useMemo(()=>catalog.script.filter(x=>x.kind==='addon'&&x.constraintCategory),[catalog.script]), derivedOpening=useMemo(()=>catalog.batch.filter(x=>['batch.hook-adaptation','batch.original-director','batch.viral-director'].includes(x.slot)),[catalog.batch]), video=useMemo(()=>catalog.batch.filter(x=>x.slot==='batch.video-meta'),[catalog.batch]), visual=useMemo(()=>catalog.batch.filter(x=>x.slot==='batch.visual-meta'),[catalog.batch]);
	 const patch=(key,v)=>setConfig(c=>({...c,[key]:{...c[key],...v}}));
	 const selectVideoPrompt=selection=>setConfig(current=>({...current,video:{...current.video,...selection,enabled:true}}));
	 async function save(){if(!batch?.id)return false;setSaving(true);try{await saveBatchSettings(batch.id,{patch:{aiPromptConfig:config},expectedRevision:revision});await onSaved?.();message.success('已保存当前批量的 AI 推理规则。');return true}catch(e){message.error(e?.message||'保存 AI 推理配置失败');return false}finally{setSaving(false)}}
	 async function savePreset(){const name=presetName.trim();if(!name)return message.warning('请填写预设名称');setPresetBusy(true);try{const result=await createConfigVersion({name,config:{type:'ai-reasoning-preset',settings:{},aiPromptConfig:config}});const saved=result?.configVersion||result;await onPresetsChanged?.();setSelectedPresetId(saved?.id||'');setPresetName('');message.success('AI 推理预设已保存。')}catch(error){message.error(error?.message||'保存 AI 推理预设失败');}finally{setPresetBusy(false)}}
	 async function renamePreset(){const name=presetName.trim();if(!selectedPreset)return message.warning('请先选择要重命名的预设');if(!name)return message.warning('请填写新的预设名称');setPresetBusy(true);try{await renameConfigVersion(selectedPreset.id,name);await onPresetsChanged?.();setPresetName('');message.success('AI 推理预设已重命名。')}catch(error){message.error(error?.message||'重命名 AI 推理预设失败');}finally{setPresetBusy(false)}}
	 function applyPreset(){const saved=aiPresetConfig(selectedPreset);if(!saved)return message.warning('所选预设内容无效');setConfig(normalize(saved,batch));message.success('预设已载入当前编辑区；点击“保存当前作品配置”后生效。');}
 const items=[
 {key:'assets',label:'资产设置',children:<Rule title="人物场景道具提示词" desc="选择一套完整资产方案；H3 会在后台自动完成事实提取与全部人物外形编译。" value={config.assets} books={usable} onChange={v=>patch('assets',v)}><Field label="人物场景道具提示词" records={extract} value={config.assets.extraction} loading={loading} onChange={v=>patch('assets',{extraction:v})}/></Rule>},
 {key:'constraints',label:'约束设置',children:<Rule title="后续视频生产约束" desc="直接复用剧本生成的五层约束规则。" value={config.constraints} books={usable} onChange={v=>patch('constraints',v)}><ConstraintLayers value={config.constraints} records={constraints} loading={loading} onChange={v=>patch('constraints',v)}/></Rule>},
 {key:'derived-opening',label:'衍生开篇',children:<Rule title="衍生开篇提示词" desc="统一指定小说正文生成候选时默认使用的提示词；单书正文中仍可临时改选。" value={config.derivedOpening} books={usable} onChange={v=>patch('derivedOpening',v)}><Field label="衍生开篇" records={derivedOpening} value={config.derivedOpening} loading={loading} onChange={v=>patch('derivedOpening',v)}/></Rule>},
 {key:'video',label:'视频设置',children:<Rule required title="视频提示词" desc="每次导演分镜都必须使用一个视频提示词；“分镜元提示词（自动组合）”是其中一个选项。" value={config.video} books={usable} onChange={v=>patch('video',v)}><Field required label="视频提示词" records={video} value={config.video} loading={loading} onChange={selectVideoPrompt}/></Rule>},
 {key:'visual',label:'画面设置',children:<Rule title="画面提示词" desc="默认关闭，仅用于画面图片，绝不写入视频提示词。" value={config.visual} books={usable} onChange={v=>patch('visual',v)}><Field label="画面提示词" records={visual} value={config.visual} loading={loading} onChange={v=>patch('visual',v)}/></Rule>}
 ];
	 return <><Modal title={<div className="batch-factory-ai-title"><span>AI 推理</span><Tooltip title="AI 推理预设"><Button type="text" icon={<SettingOutlined />} onClick={()=>setPresetOpen(true)} aria-label="AI 推理预设"/></Tooltip></div>} open={open} onCancel={onClose} width={900} className="batch-factory-ai-modal" footer={<Space><Button onClick={onClose}>取消</Button><Button loading={saving} onClick={save}>保存当前作品配置</Button><Button type="primary" loading={running} disabled={!runAvailable||saving||running||!usable.length} title={runAvailable?'先保存选择的系统预设词，再执行统一 AI 推理。':runReason} onClick={async()=>{if(await save())await onRun?.()}}>保存并统一生成</Button></Space>}><Alert type="info" showIcon message="从个人中心的已发布预设词选择" description="资产、约束、衍生开篇、视频和画面均按对应槽位调用；衍生开篇可作为单书正文中的默认选择。预设正文不展示给浏览器。"/>{error?<Alert type="warning" showIcon message="系统预设词读取失败" description={error}/>:null}<Tabs items={items}/>{!runAvailable?<Alert type="warning" showIcon message="当前不能执行 AI 推理" description={runReason||'请先完成引擎配置。'}/>:null}</Modal><Modal title="AI 推理预设" open={presetOpen} onCancel={()=>setPresetOpen(false)} footer={null} width={620} className="batch-factory-ai-preset-modal"><Space direction="vertical" size={14} style={{width:'100%'}}><Alert type="info" showIcon message="保存与载入当前全部 AI 推理模块的配置" description="载入后仍须保存当前作品配置才会生效。"/><label className="batch-factory-ai-field"><span>已保存预设</span><Select allowClear value={selectedPresetId||undefined} onChange={setSelectedPresetId} options={aiPresets.map(version=>({value:version.id,label:version.name}))} placeholder="选择 AI 推理预设"/></label><Space wrap><Button disabled={!selectedPreset} onClick={applyPreset}>载入预设</Button></Space><label className="batch-factory-ai-field"><span>{selectedPreset?'预设新名称':'新预设名称'}</span><Input value={presetName} onChange={event=>setPresetName(event.target.value)} placeholder={selectedPreset?selectedPreset.name:'例如：前贴女频短剧'} maxLength={255}/></label><Space wrap><Button type="primary" loading={presetBusy} onClick={savePreset}>保存为新预设</Button><Button loading={presetBusy} disabled={!selectedPreset} onClick={renamePreset}>重命名所选预设</Button></Space></Space></Modal></>;
}
